import type { Metadata } from "next";

import LayoutDrawer from "@/features/LayoutDrawer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <LayoutDrawer responsive={true}>
      <div style={{ overflowY: "auto" }}>{children}</div>
    </LayoutDrawer>
  );
}
