import "./global.css";

import { defaultPalette, defaultSize } from "@idealjs/camphora-styled";
import clsx from "clsx";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        style={{ margin: 0, height: "100vh" }}
        className={clsx(defaultSize, defaultPalette)}
      >
        {children}
      </body>
    </html>
  );
}
