import "./global.css";

import {
  button,
  buttonGhost,
  clickReaction,
  clickReactionInput,
  drawer,
  drawerContent,
  drawerMenu,
  drawerOverlay,
  drawerSide,
  hFull,
  navbar,
} from "@idealjs/camphora-styled";
import { hScreen } from "@idealjs/camphora-styled";
import clsx from "clsx";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

style

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(hScreen)}>
        <div className={clsx(clickReaction, drawer, hFull)}>
          <input id="test" type="checkbox" className={clickReactionInput} />
          <div className={drawerContent}>
            <nav className={navbar}>
              <label
                htmlFor="test"
                className={clsx(button, buttonGhost, "select-none")}
              >
                open
              </label>
            </nav>
            {children}
          </div>
          <div className={clsx(drawerSide)}>
            <label htmlFor="test" className={drawerOverlay}></label>
            <div className={drawerMenu}>menu</div>
          </div>
        </div>
      </body>
    </html>
  );
}
